### ISSUE TITLE
A single room is offering 999 max Paxes

### ISSUE THREAD

**Issue by Tahir-MatrixAMS** [hotelbeds-sdk/hotel-api-sdk-php#121]
the following data is get from contect api type/room. A single room is offering 999 max paxes how can we justify this.
e.g ( "code": "BUN.DX-GV",
"type": "BUN",
"characteristic": "DX-GV",
"minPax": 0,
**"maxPax": 999,**
**"maxAdults": 999,**
"maxChildren": 3,
"minAdults": 1,
"description": "BUNGALOW DELUXE GARDEN VIEW",
"typeDescription": {
"content": "BUNGALOW"
},
"characteristicDescription": {
"content": "DELUXE GARDEN VIEW"
}
)
Note: Please reply soon thanks

**Comment by vmavromatis** [comment]
Hello @Tahir-MatrixAMS, I was able to confirm that this is how the room type is registered in the database. I will notify Content team regarding this issue. In the meantime, please let me know if you come accross the hotel which has this room code; however if a hotel does not contain this exact room code, there is practically no problem.

In the meantime let me kindly remind you that it's preferable that you address all server-side related issues to the apitude@hotelbeds.com address as this place is reserved for users of our SDK libraries.

**Comment by pierrejoye** [comment]
afaik this is fixed in latest Aptitude release. @

**Comment by vmavromatis** [comment]
Hi @pierrejoye, unfortunately I cannot confirm as it's still showing the same (on LIVE environment):

http://api.hotelbeds.com/hotel-content-api/1.0/types/rooms?fields=all&language=ENG&from=601&to=699
```java
        {
            "code": "BUN.DX-GV",
            "type": "BUN",
            "characteristic": "DX-GV",
            "minPax": 0,
            "maxPax": 999,
            "maxAdults": 999,
            "maxChildren": 3,
            "minAdults": 1,
            "description": "BUNGALOW DELUXE GARDEN VIEW",
            "typeDescription": {
                "languageCode": "ENG",
                "content": "BUNGALOW"
            },
            "characteristicDescription": {
                "languageCode": "ENG",
                "content": "DELUXE GARDEN VIEW"
            }
        },
```

Are you receiving a similar response?

**Comment by travelta** [comment]
I fetched all rooms and there are allot of rooms with maxpax 99 or 999. This cant be right. How do other hotelbeds integrators do this? This is from the test environment btw

![Schermafbeelding 2020-02-25 om 11 41 39](https://user-images.githubusercontent.com/22450172/75239966-e0348900-57c3-11ea-9695-4d2b246cc6da.png)
