### ISSUE TITLE
AT_HOTEL filter not working

### ISSUE THREAD

**Issue by suneel11** [hotelbeds-sdk/hotel-api-sdk-php#143]
Hello there 

I am not getting any response for the filter AT_HOTEL, it always says 
[hotels] => stdClass Object  (
     [total] => 0
). While it provides me the list for the hotels for the filter AT_WEB.

Why there are no hotels for the filter AT_HOTEL for any of the location.

**Comment by vmavromatis** [comment]
Hi @suneel11, It might be the case that AT_HOTEL is not configured to show for your apikey. Can you please share your apikey (not secret)? Thank you.

Regards,
Vasilis

**Comment by suneel11** [comment]
yes sure

here you go:    aq48k2vwag2evqfmyvd5zk32

**Comment by vmavromatis** [comment]
Done, you should now be receiving AT_HOTEL rates.

However, I see that you are over rate
```
Connection →keep-alive
Content-Length →28
Content-Type →text/xml
Date →Thu, 30 Aug 2018 13:19:08 GMT
Retry-After →38452
Server →Mashery Proxy
X-Error-Detail-Header →Account Over Rate Limit
X-Mashery-Error-Code →ERR_403_DEVELOPER_OVER_RATE
X-Mashery-Responder →prod-j-worker-hotelbeds-eu-west-1c-23.mashery.com
X-Plan-QPS-Allotted →2
X-Plan-QPS-Current →1
X-Plan-Quota-Allotted →50
X-Plan-Quota-Current →51
X-Plan-Quota-Reset →Friday, August 31, 2018 12:00:00 AM GMT
X-PlanMethod-QPS-Allotted →2
X-PlanMethod-QPS-Current →1
```
Could you please wait until midnight GMT for the quota to reset? Hope it's fine.

**Comment by suneel11** [comment]
Hello


I am still not getting any results for the AT_HOTEL, please check for that:
*Here is the request*
{
    "stay":{
        "checkIn":"2018-09-04",
        "checkOut":"2018-09-10",
        "shiftDays":"2"

    },
    "occupancies":[
        {
            "rooms":"1",
            "adults":2,
            "children":0,
            "paxes":[
                {
                    "type":"AD",
                    "age":30

                },{
                    "type":"AD",
                    "age":30

                }
            ]

        }
    ],
    "geolocation":{
        "longitude":-80.1917902,
        "latitude":25.7616798,
        "radius":200,
        "unit":"mi"
    },
    "filter":{
        "paymentType":"AT_HOTEL"
    }

}
*Here is the response I am getting*


*{ "auditData": { "processTime": "130", "timestamp": "2018-08-31
06:30:51.173", "requestHost": "23.23.79.233", "serverId":
"sa37AUX3ROLBLIS.env", "environment": "[int]", "release":
"4e21884df45756e39e474aab3fe4fbc6adfcbcb0", "token":
"45cbd8cb-c947-482c-906c-3f2521cce346", "internal":
"0||US|10|0|0|||||||AT_HOTEL|||||0||1~1~2~0|0|0||0|aq48k2vwag2evqfmyvd5zk32|||"
}, "hotels": { "total": 0 } }*
Is there anything I am doing wrong. Please help me with this.



Thanks & Regards

**Comment by vmavromatis** [comment]
I believe there is just no hotels available for the location/dates you are searching. Try this one:
```
<availabilityRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <stay checkIn="2018-12-15" checkOut="2018-12-16"/>
  <occupancies>
    <occupancy rooms="1" adults="1" children="0"/>
  </occupancies>
  <geolocation latitude="39.57119" longitude="2.646633999999949" radius="20" unit="km"/>
 <filter paymentType="AT_HOTEL" />
</availabilityRQ>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<availabilityRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages">
    <auditData processTime="78" timestamp="2018-08-31 09:23:52.438" requestHost="212.66.164.12" serverId="sa3RKSJACHXE79K.env" environment="[int]" release="4e21884df45756e39e474aab3fe4fbc6adfcbcb0" token="a59bc0eb-dc9c-4e1d-875d-52135ab32817" internal="0|848B66D4A5574461AD81A95AF894A3460923|US|10|5|33|||||||AT_HOTEL|||||28||1~1~1~0|0|0||0|aq48k2vwag2evqfmyvd5zk32|||"/>
    <hotels checkIn="2018-12-15" total="5" checkOut="2018-12-16">
        <hotel code="168" name="Eurostars Marivent" categoryCode="4EST" categoryName="4 STARS" destinationCode="PMI" destinationName="Majorca" zoneCode="86" zoneName="Cala Major" latitude="39.5526831653502" longitude="2.61092998087406" minRate="78.35" maxRate="156.70" currency="USD">
            <rooms>
                <room code="SGL.ST" name="SINGLE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|168|SGL.ST|NRF-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="78.35" sellingRate="90.06" hotelSellingRate="76.50" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="11.71" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|96465|0" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="90.06" hotelAmount="76.50" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="7.84" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|SGL.ST|CG-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="87.05" sellingRate="100.06" hotelSellingRate="85.00" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="13.01" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="100.06" hotelAmount="85.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="8.71" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|SGL.ST|NRF-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="88.49" sellingRate="101.71" hotelSellingRate="86.40" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="13.22" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|98811|0" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="101.71" hotelAmount="86.40" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="8.85" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|SGL.ST|CG-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="98.32" sellingRate="113.01" hotelSellingRate="96.00" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="14.69" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="113.01" hotelAmount="96.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="9.83" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
                <room code="DUS.ST" name="DOUBLE SINGLE USE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|168|DUS.ST|NRF-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="82.96" sellingRate="95.35" hotelSellingRate="81.00" hotelCurrency="EUR" hotelMandatory="true" allotment="20" commission="12.40" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|96465|0" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="95.35" hotelAmount="81.00" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="8.30" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|DUS.ST|CG-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="92.17" sellingRate="105.95" hotelSellingRate="90.00" hotelCurrency="EUR" hotelMandatory="true" allotment="20" commission="13.77" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="105.95" hotelAmount="90.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="9.22" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|DUS.ST|NRF-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="93.10" sellingRate="107.01" hotelSellingRate="90.90" hotelCurrency="EUR" hotelMandatory="true" allotment="20" commission="13.91" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|98811|0" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="107.01" hotelAmount="90.90" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="9.31" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|DUS.ST|CG-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="103.44" sellingRate="118.90" hotelSellingRate="101.00" hotelCurrency="EUR" hotelMandatory="true" allotment="20" commission="15.46" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="118.90" hotelAmount="101.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="10.34" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
                <room code="TPL.ST" name="TRIPLE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|168|TPL.ST|NRF-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="110.61" sellingRate="127.14" hotelSellingRate="108.00" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="16.53" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|96465|0" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="127.14" hotelAmount="108.00" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="11.06" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|TPL.ST|CG-ALL|RO||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="122.90" sellingRate="141.26" hotelSellingRate="120.00" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="18.36" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="RO" boardName="ROOM ONLY" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="141.26" hotelAmount="120.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="12.29" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|TPL.ST|NRF-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="141.03" sellingRate="162.10" hotelSellingRate="137.70" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="21.07" commissionVAT="0.00" commissionPCT="13.00" rateCommentsId="1|98811|0" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="162.10" hotelAmount="137.70" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="14.10" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|168|TPL.ST|CG-ALL BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="156.70" sellingRate="180.11" hotelSellingRate="153.00" hotelCurrency="EUR" hotelMandatory="true" allotment="5" commission="23.41" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="180.11" hotelAmount="153.00" hotelCurrency="EUR" from="2018-12-14T12:00:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="15.67" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
            </rooms>
            <creditCards>
                <creditCard code="VI" name="VISA-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="AE" name="AMEX-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MA" name="SWITCH-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MC" name="ECMC-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="VE" name="VISA-SSL" paymentType="AT_HOTEL"/>
            </creditCards>
        </hotel>
        <hotel code="615461" name="Icon Rosetó by Petit Palace" categoryCode="SUP" categoryName="SUPERIOR 4*" destinationCode="PMI" destinationName="Majorca" zoneCode="10" zoneName="Palma" latitude="39.572076" longitude="2.649496" minRate="203.81" maxRate="203.81" currency="USD">
            <rooms>
                <room code="DBL.ST" name="DOUBLE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|615461|DBL.ST|CG-TODOSBB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="203.81" sellingRate="234.26" hotelSellingRate="199.00" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="30.45" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="234.26" hotelAmount="199.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="20.38" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
            </rooms>
            <creditCards>
                <creditCard code="E6" name="EURO6000-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="VI" name="VISA-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="AE" name="AMEX-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MC" name="ECMC-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="JC" name="JCB-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="DC" name="DINERS-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="VE" name="VISA-SSL" paymentType="AT_HOTEL"/>
            </creditCards>
        </hotel>
        <hotel code="297" name="Occidental Playa de Palma" categoryCode="4EST" categoryName="4 STARS" destinationCode="PMI" destinationName="Majorca" zoneCode="20" zoneName="Playa de Palma" latitude="39.516336" longitude="2.749349" minRate="53.26" maxRate="88.08" currency="USD">
            <rooms>
                <room code="DUS.ST" name="DOUBLE SINGLE USE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|OFE-BAJABB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="53.26" sellingRate="61.21" hotelSellingRate="52.00" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="7.96" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="30.61" hotelAmount="26.00" hotelCurrency="EUR" from="2018-12-07T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="5.33" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="042" name="Special Offer" remark="Special offer . Special offer"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|OFE-BAJAHB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="53.97" sellingRate="62.04" hotelSellingRate="52.70" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="8.06" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="31.02" hotelAmount="26.35" hotelCurrency="EUR" from="2018-12-07T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="5.40" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="042" name="Special Offer" remark="Special offer. Special offer"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|CG-BAR17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="59.40" sellingRate="68.28" hotelSellingRate="58.00" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="8.88" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="68.28" hotelAmount="58.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="5.94" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|OFE-BAJAAI|AI||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="60.94" sellingRate="70.04" hotelSellingRate="59.50" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="9.11" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="AI" boardName="ALL INCLUSIVE" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="35.02" hotelAmount="29.75" hotelCurrency="EUR" from="2018-12-07T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="6.09" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="042" name="Special Offer" remark="Special offer. Special offer"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|CG-BAR17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="63.50" sellingRate="72.99" hotelSellingRate="62.00" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="9.49" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="72.99" hotelAmount="62.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="6.35" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|297|DUS.ST|CG-BAR17AI|AI||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="88.08" sellingRate="101.24" hotelSellingRate="86.00" hotelCurrency="EUR" hotelMandatory="true" allotment="30" commission="13.16" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="AI" boardName="ALL INCLUSIVE" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="101.24" hotelAmount="86.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="8.81" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
            </rooms>
            <creditCards>
                <creditCard code="VI" name="VISA-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="AE" name="AMEX-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MA" name="SWITCH-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MC" name="ECMC-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="DC" name="DINERS-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="VE" name="VISA-SSL" paymentType="AT_HOTEL"/>
            </creditCards>
        </hotel>
        <hotel code="77" name="Barcelo Illetas Albatros" categoryCode="4EST" categoryName="4 STARS" destinationCode="PMI" destinationName="Majorca" zoneCode="89" zoneName="Illetes" latitude="39.542286" longitude="2.595543" minRate="83.31" maxRate="512.08" currency="USD">
            <rooms>
                <room code="DUS.SU" name="DOUBLE SINGLE USE SUPERIOR">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU|NRF-17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="83.31" sellingRate="95.75" hotelSellingRate="81.34" hotelCurrency="EUR" hotelMandatory="true" allotment="61" commission="12.45" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="95.75" hotelAmount="81.34" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="8.33" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU|CG-BAR17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="100.37" sellingRate="115.37" hotelSellingRate="98.00" hotelCurrency="EUR" hotelMandatory="true" allotment="60" commission="15.00" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="115.37" hotelAmount="98.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="10.04" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU|NRF-17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="107.25" sellingRate="123.28" hotelSellingRate="104.72" hotelCurrency="EUR" hotelMandatory="true" allotment="61" commission="16.03" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="123.28" hotelAmount="104.72" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="10.73" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU|CG-BAR17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="121.88" sellingRate="140.09" hotelSellingRate="119.00" hotelCurrency="EUR" hotelMandatory="true" allotment="60" commission="18.21" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="140.09" hotelAmount="119.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="12.19" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
                <room code="DUS.SS" name="DOUBLE SINGLE USE SIDE SEA VIEW">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SS|NRF-17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="102.86" sellingRate="118.23" hotelSellingRate="100.43" hotelCurrency="EUR" hotelMandatory="true" allotment="22" commission="15.37" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="118.23" hotelAmount="100.43" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="10.29" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SS|CG-BAR17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="123.92" sellingRate="142.44" hotelSellingRate="121.00" hotelCurrency="EUR" hotelMandatory="true" allotment="22" commission="18.52" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="142.44" hotelAmount="121.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="12.39" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SS|CG-BAR17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="145.43" sellingRate="167.16" hotelSellingRate="142.00" hotelCurrency="EUR" hotelMandatory="true" allotment="22" commission="21.73" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="167.16" hotelAmount="142.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="14.54" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SS|NRF-17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="512.08" sellingRate="588.60" hotelSellingRate="500.00" hotelCurrency="EUR" hotelMandatory="true" allotment="22" commission="76.52" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="588.60" hotelAmount="500.00" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="51.21" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                    </rates>
                </room>
                <room code="DUS.SU-VM" name="DOUBLE SINGLE USE SUPERIOR FRONT SEA VIEW">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU-VM|NRF-17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="120.71" sellingRate="138.74" hotelSellingRate="117.86" hotelCurrency="EUR" hotelMandatory="true" allotment="10" commission="18.04" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="138.74" hotelAmount="117.86" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="12.07" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU-VM|CG-BAR17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="145.43" sellingRate="167.16" hotelSellingRate="142.00" hotelCurrency="EUR" hotelMandatory="true" allotment="10" commission="21.73" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="167.16" hotelAmount="142.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="14.54" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU-VM|NRF-17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="146.91" sellingRate="168.86" hotelSellingRate="143.44" hotelCurrency="EUR" hotelMandatory="true" allotment="10" commission="21.95" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="168.86" hotelAmount="143.44" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="14.69" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.SU-VM|CG-BAR17HB|HB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="166.94" sellingRate="191.88" hotelSellingRate="163.00" hotelCurrency="EUR" hotelMandatory="true" allotment="10" commission="24.94" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="HB" boardName="HALF BOARD" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="191.88" hotelAmount="163.00" hotelCurrency="EUR" from="2018-12-13T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="16.69" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
                <room code="DUS.VM" name="DOUBLE SINGLE USE SUPERIOR SIDE SEA VIEW">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|77|DUS.VM|NRF-17BB|BB||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NRF" rateType="BOOKABLE" net="123.92" sellingRate="142.44" hotelSellingRate="121.00" hotelCurrency="EUR" hotelMandatory="true" allotment="22" commission="18.52" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="BB" boardName="BED AND BREAKFAST" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="142.44" hotelAmount="121.00" hotelCurrency="EUR" from="2018-08-30T23:59:00+02:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="12.39" currency="EUR"/>
                                <tax included="false" amount="3.30" currency="EUR" clientAmount="3.88" clientCurrency="USD"/>
                            </taxes>
                            <promotions>
                                <promotion code="073" name="Non-refundable rate. No amendments permitted"/>
                            </promotions>
                        </rate>
                    </rates>
                </room>
            </rooms>
            <creditCards>
                <creditCard code="VI" name="VISA-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="AE" name="AMEX-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MC" name="ECMC-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="DC" name="DINERS-SSL" paymentType="AT_HOTEL"/>
            </creditCards>
        </hotel>
        <hotel code="311" name="Seramar Luna-Luna Park" categoryCode="3EST" categoryName="3 STARS" destinationCode="PMI" destinationName="Majorca" zoneCode="75" zoneName="S'Arenal" latitude="39.497949" longitude="2.753301" minRate="1024.16" maxRate="1024.16" currency="USD">
            <rooms>
                <room code="DUS.ST" name="DOUBLE SINGLE USE STANDARD">
                    <rates>
                        <rate rateKey="20181215|20181216|H|1|311|DUS.ST|PVP-SHORTSTAY|AI||1~1~0||N@848B66D4A5574461AD81A95AF894A3460923" rateClass="NOR" rateType="BOOKABLE" net="1024.16" sellingRate="1177.20" hotelSellingRate="1000.00" hotelCurrency="EUR" hotelMandatory="true" allotment="1" commission="153.04" commissionVAT="0.00" commissionPCT="13.00" paymentType="AT_HOTEL" packaging="false" boardCode="AI" boardName="ALL INCLUSIVE" rooms="1" adults="1" children="0">
                            <cancellationPolicies>
                                <cancellationPolicy amount="1177.20" hotelAmount="1000.00" hotelCurrency="EUR" from="2018-12-09T23:59:00+01:00"/>
                            </cancellationPolicies>
                            <taxes allIncluded="false">
                                <tax included="true" percent="10.00" amount="102.42" currency="EUR"/>
                                <tax included="false" amount="2.20" currency="EUR" clientAmount="2.59" clientCurrency="USD"/>
                            </taxes>
                        </rate>
                    </rates>
                </room>
            </rooms>
            <creditCards>
                <creditCard code="VI" name="VISA-SSL" paymentType="AT_HOTEL"/>
                <creditCard code="MC" name="ECMC-SSL" paymentType="AT_HOTEL"/>
            </creditCards>
        </hotel>
    </hotels>
</availabilityRS>
```

**Comment by suneel11** [comment]
Hello

Thanks for the help may be it's due to the location that I am not getting
the hotels as I entered other location it provides me the response. Thanks
again for that.

**Comment by vmavromatis** [comment]
No problem, good to be of help. Let me know if you need anything else.

Regards,
Vasilis

**Comment by suneel11** [comment]
Hello there

I am getting an error "

*There is not enough space in the service for all the passengers" at the
time of booking.*

*My api key is same mentioned above.*

*Response  *



*Array ( [@attributes] => Array ( [schemaLocation] =>
http://www.hotelbeds.com/schemas/messages
<http://www.hotelbeds.com/schemas/messages> ) [auditData] => Array (
[@attributes] => Array ( [processTime] => 826 [timestamp] => 2018-09-03
10:41:40.252 [requestHost] => 198.71.230.16 [serverId] =>
sa37AUX3ROLBLIS.env#PL [environment] => [int] [release] =>
4e21884df45756e39e474aab3fe4fbc6adfcbcb0 [token] =>
3aeee454-caa0-46a4-b538-f41abbadef67 [internal] =>
0|BB77524FF324494D90D08B5C76A3211E1037|US|10|24|735|||||||AT_HOTEL||||R|267|6|1~1~1~0||0||0|aq48k2vwag2evqfmyvd5zk32|||
) ) [error] => Array ( [code] =>
PRODUCT_ERROR-3aeee454-caa0-46a4-b538-f41abbadef67 [message] =>
ProductException(BOOKING_CONFIRM, There is not enough space in the service
for all the passengers.) ) )*

Please help me with this.


Thanks & Regards

**Comment by vmavromatis** [comment]
Hello @suneel11 

Can you please post your Booking Request? This is a `1~1~0` room (one room one adult no children), I would like to make sure that you are not asking for more than 1 rooms or more than 1 adults. 

Regards,
Vasilis

**Comment by suneel11** [comment]
Hello @vmavromatis

Here is the rate key and response

**RateKey**      20180904|20180910|H|102|94962|DBL.SU|OFE-LES3NOCHES|RO||1~1~0||N@BB77524FF324494D90D08B5C76A3211E1037

**Response**
Array
(
    [@attributes] => Array
        (
            [schemaLocation] => http://www.hotelbeds.com/schemas/messages
        )

    [auditData] => Array
        (
            [@attributes] => Array
                (
                    [processTime] => 540
                    [timestamp] => 2018-09-03 11:04:14.546
                    [requestHost] => 198.71.230.16
                    [serverId] => sa37AUX3ROLBLIS.env#PL
                    [environment] => [int]
                    [release] => 4e21884df45756e39e474aab3fe4fbc6adfcbcb0
                    [token] => 3cde7096-4855-4d3d-a12c-615dfb9406cc
                    [internal] => 0|BB77524FF324494D90D08B5C76A3211E1037|US|10|24|735|||||||AT_HOTEL||||R|267|6|1~1~1~0||0||0|aq48k2vwag2evqfmyvd5zk32|||
                )

        )

    [error] => Array
        (
            [code] => PRODUCT_ERROR-3cde7096-4855-4d3d-a12c-615dfb9406cc
            [message] => ProductException(BOOKING_CONFIRM, There is not enough space in the service for all the passengers.)
        )

)

**Comment by suneel11** [comment]
Here is the request data

<bookingRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance">
<holder name="test" surname="test"/>
<rooms>
<room rateKey="20180904|20180910|H|102|94962|DBL.SU
|NRF-EB3DIASRO|RO||1~1~0||N@1C6D75F3E72C4478888FDEDBCB2192051134">
<paxes>
<pax roomId="1" type="AD" name="sk" surname="sk"/>
</paxes>
</room>
</rooms>
<paymentData>
<paymentCard>
<cardHolderName>test</cardHolderName>
<cardType>VI</cardType>
<cardNumber>4242424242424242</cardNumber>
<expiryDate>2020</expiryDate>
<cardCVC>321</cardCVC>
</paymentCard>
<contactData>
<email>suneel.kumar@xcelance.com</email>
<phoneNumber>1234567890</phoneNumber>
</contactData>
</paymentData>
<clientReference>My booking reference</clientReference>
</bookingRQ>


Thanks & Regards.

On Mon, Sep 3, 2018 at 2:52 PM, Vasilis Mavromatis <notifications@github.com

**Comment by vmavromatis** [comment]
For the first error, there may be issues with the TEST environment as it's not as stable as LIVE. I will try to have a look and let you know ASAP. 
For the second error, it's just prohibiting you for booking because the price change is greater than the price tolerance threshold set at client configuration (normally 2%).

In the meanwhile, please try to book different rates, and see if you are able to. 

Regards,
Vasilis

**Comment by suneel11** [comment]
Ok, but please provide me the solution for the first error.

Thanks & Regards.

On Mon, Sep 3, 2018 at 6:35 PM, Vasilis Mavromatis <notifications@github.com
