### ISSUE TITLE
Price changed during the booking process error

### ISSUE THREAD

**Issue by advacom** [hotelbeds-sdk/hotel-api-sdk-php#145]
Hi,

I'm currently working with the disney un-official hotels and no matter what booking I make i'm getting the following error : 

> Internal Server Error: PRODUCT_ERROR-1acbaed5-d0b5-4397-8d39-bad1ac8e35b2 ProductException(BOOKING_CONFIRM, Price changed during the booking process

After some digging I found the following https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/133 link. Could it be this bug is still active?

Attached my request:

{  
   "holder":{  
      "name":"TEST",
      "surname":"TEST"
   },
   "rooms":[  
      {  
         "rateKey":"20190124|20190126|W|197|54977|QUA.ST|FIT RO|RO||1~2~2|48~48|N@09B91C35EE0648138AA09FA0903A53070945",
         "paxes":[  
            {  
               "age":18,
               "type":"AD",
               "roomId":1,
               "name":"lars",
               "surname":"lars"
            },
            {  
               "age":18,
               "type":"AD",
               "roomId":1,
               "name":"lars",
               "surname":"lars"
            },
            {  
               "age":10,
               "type":"CH",
               "roomId":1,
               "name":"lars",
               "surname":"lars"
            },
            {  
               "age":10,
               "type":"CH",
               "roomId":1,
               "name":"lars",
               "surname":"lars"
            }
         ]
      }
   ],
   "clientReference":"TEST"
}

@vmavromatis, Could you please be so kind to have a look at this.

Thanks in advance,

**Comment by vmavromatis** [comment]
Hi @advacom AFAIK this issue was fixed, I just tried to reproduce and was able to book just fine. Can you please share your apikey? Maybe there is a setting related to your apikey causing this.

**Comment by advacom** [comment]
Hi @vmavromatis, The apikey is qnnv8npksm227vv5nscjwdzs

Just tested, still getting same results

**Comment by vmavromatis** [comment]
Hi @advacom, I just used a workaround (booked for late date - Dec 2019). The team is reviewing but this is most likely a cache sync issue that affects only the test environment. Can you please use the workaround while the team is working on fixing the issue? Thank you very much in advance.

FYI the booking I made and cancelled is **197-4327947**
```{
    "auditData": {
        "processTime": "3184",
        "timestamp": "2018-11-26 12:23:38.049",
        "requestHost": "212.66.164.14",
        "serverId": "sa3RKSJACHXE79K.env#PL",
        "environment": "[int]",
        "release": "4e21884df45756e39e474aab3fe4fbc6adfcbcb0",
        "token": "cf89cd0d-d75a-4694-8573-236101a48b78",
        "internal": "0|9E65576D0E6542A7B39CBC58DB56A44B1223|NL|01|77|443|||||||||1.03|C|R|880|1|1~1~2~0|0|0||0|qnnv8npksm227vv5nscjwdzs|||"
    },
    "booking": {
        "reference": "197-4327947",
        "clientReference": "INTEGRATIONAGEN",
        "creationDate": "2018-11-26",
        "status": "CONFIRMED",
        "modificationPolicies": {
            "cancellation": true,
            "modification": true
        },
        "creationUser": "qnnv8npksm227vv5nscjwdzs",
        "holder": {
            "name": "INTEGRATIONTESTFIRSTNAME",
            "surname": "INTEGRATIONTESTLASTNAME"
        },
        "hotel": {
            "checkOut": "2019-12-20",
            "checkIn": "2019-12-19",
            "code": 163988,
            "name": "Berkeley Hotel",
            "categoryCode": "3EST",
            "categoryName": "3 STARS",
            "destinationCode": "PAR",
            "destinationName": "Paris",
            "zoneCode": 18,
            "zoneName": "Arr14/15:Montparnasse-T. Eiffel",
            "latitude": "48.842966",
            "longitude": "2.324196",
            "rooms": [
                {
                    "status": "CONFIRMED",
                    "id": 1,
                    "code": "TWN.SU",
                    "name": "TWIN SUPERIOR",
                    "paxes": [
                        {
                            "roomId": 1,
                            "type": "AD",
                            "name": "First Adult Name"
                        },
                        {
                            "roomId": 1,
                            "type": "AD",
                            "name": "First Adult Name",
                            "surname": "Surname"
                        }
                    ],
                    "rates": [
                        {
                            "rateClass": "NOR",
                            "net": "179.95",
                            "rateComments": "1x TWIN Estimated total amount of taxes & fees for this booking: 3.30 Euro   payable on arrival  \r. Car park NO   . Key Collection 07:00 – 20:00. Check-in hour 14:00 – 20:00. ",
                            "paymentType": "AT_WEB",
                            "packaging": false,
                            "boardCode": "RO",
                            "boardName": "ROOM ONLY",
                            "cancellationPolicies": [
                                {
                                    "amount": "179.95",
                                    "from": "2019-12-18T18:00:00+01:00"
                                }
                            ],
                            "rooms": 1,
                            "adults": 2,
                            "children": 0
                        }
                    ]
                }
            ],
            "totalNet": "179.95",
            "currency": "EUR",
            "supplier": {
                "name": "HOTELBEDS PRODUCT,S.L.U.",
                "vatNumber": "ESB38877676"
            }
        },
        "invoiceCompany": {
            "code": "E14",
            "company": null,
            "registrationNumber": null
        },
        "totalNet": 179.95,
        "pendingAmount": 179.95,
        "currency": "EUR"
    }
}
```

**Comment by advacom** [comment]
Hi @vmavromatis, What workaround do you mean exactly? Booking in December 2019 doesn't give me any available results.

**Comment by vmavromatis** [comment]
@advacom can you please try the following:
```
<availabilityRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
 <stay checkIn="2019-12-19" checkOut="2019-12-20"/>
 <occupancies>
        <occupancy rooms="1" adults="2" children="0"/>
 </occupancies>
 <destination code="PAR"/>
</availabilityRQ>  
```

That should list all hotels in Paris destination

**Comment by advacom** [comment]
Hi @vmavromatis, Thanks for your quick answer. This indeed returns all hotels within Paris but by code is based only on the Disney hotels, since this is the only information that we have to implement within the website.

**Comment by BeauCOTravel** [comment]
Hi @vmavromatis, in what time frame do you expect to be able to solve the problem? We are in the middle of development and need a quick solution. Thank you, Beau Meels, C&O Travel

**Comment by vmavromatis** [comment]
Can you please share a few hotel codes? I will try to get availability. I will keep you updated regarding this issue, marking as server-side related

**Comment by BeauCOTravel** [comment]
Thanks Vasilis. Appreciate it.
I probably have some IDs for you. Correct me if I'm wrong and I'll leave it up to Lars.

non-official Disney Hotels IDs

Vienna House Dream Castle Paris - 54 - 41106
Vienna House Magic Circus Paris - 51 -29646
Radisson Blu Hotel at Disneyland Paris - 68 - 54814
Adagio Val d’Europe - 50 - 27940
Explorers at Disneyland Paris -178 - 211989
Kyriad Disneyland Resort Paris - 69 - 64977
l’Elysée Val d’Europe - 112 - 133801
B&B Hotel Disneyland Paris - 278 - 550841
Villages Nature Paris - 288 - 595685

**Comment by vmavromatis** [comment]
@BeauCOTravel @advacom I received a date for the refresh of the TEST environment which should fix all sync issues, it's 5th of December. In the meantime, can you please try to test your integration with other products returned in Paris as shown above? Thank you, and apologies for the inconvenience.

**Comment by BeauCOTravel** [comment]
@vmavromatis we have experienced the same with the integration of the official Disney hotels. The sync of the TEST environment (on which we had to wait for a month) didn't solve the problem and we were forced to develop in the LIVE environment. Can you confirm that the TEST environment has even worked in the last year?

Sorry, but because of the history I am not happy to wait for the 5th of december with the risk of being disappointed again. Alejandro Rivas (from Hotelbeds) can confirm that this has been going on for 2 years and we NEVER had a fully functioning TEST environment.

How are we supposed to integrate the Hotelbeds product like this?
Sorry, that you have to deal with this now, but it's the reality of the project.

**Comment by vmavromatis** [comment]
@BeauCOTravel I am sorry for this. TEST has been functional for most of the cases, surely not near as stable as LIVE but should be enough for the integration phase. I will look into what is the issue with these specific hotels and get back to you - we have already raised it with IT. Hope this helps.

**Comment by vmavromatis** [comment]
@BeauCOTravel @advacom we changed the price tolerance for your account to be 10% instead of 2% for TEST environment only. Change will take about 6h-8h to propagate, please try to see if you can book then.

**Comment by advacom** [comment]
Hi @vmavromatis, 

As requested : 

```
{  
   "holder":{  
      "name":"TEST",
      "surname":"TEST"
   },
   "rooms":[  
      {  
         "rateKey":"20181227|20181229|W|197|54977|DBT.ST|GAR FIT1 NRF RO|RO||1~1~0||N@BD4AACC45B8B4CBD9A98AC79CE124FD90934",
         "paxes":[  
            {  
               "age":18,
               "type":"AD",
               "roomId":1,
               "name":"test",
               "surname":"test"
            }
         ]
      }
   ],
   "clientReference":"TEST"
}

```


**Exception Response**
"Internal Server Error: PRODUCT_ERROR-2ce008c7-3a19-4c5d-88af-3e23a49e75e8 ProductException(BOOKING_CONFIRM, Price changed during the booking process"

**Comment by vmavromatis** [comment]
Hi @advacom problem was detected, the price increase was 31% so exceeding the new threshold, changing it now to 100% (please allow few hours to refresh) and you should stop seeing this error. Please let me know if this worked.

**Comment by advacom** [comment]
Hi @vmavromatis, Thanks for your response. What is the threshold on the live environment? 
We of course have to make sure we won't get the same errors when moving to live.

**Comment by vmavromatis** [comment]
@advacom on LIVE environment you will have a seperate price tolerance (normally set at 2% or so) for which you can discuss with apitude@hotelbeds.com. I hope this helps.

**Comment by advacom** [comment]
Goodmorning Vasillis,

I was just testing this morning with the non-official hotels and ran into the following:

When starting a booking I get a payable price of €109.63 when proceeding the booking and checking with postman the total amount is €123.69. 

How is it possible that the checkrate returns a lower price than the actual booked price?

Hope you can help me out.

Thanks again,

**Comment by vmavromatis** [comment]
Good morning @advacom,

This is happening because of the price change. In this case 109.63->123.69 = 12.82% increase. As mentioned previously, these types of increases between operations (availability->confirmation or checkrates->confirmation) occur often in the TEST environment (because the cache is updated much less often than in LIVE), but are very rare in LIVE. In case they do happen in LIVE, the price tolerance will trigger and the API will return a Product error ("Price has changed") of status 500. Hope this helps.

So I take it that the issue is resolved in TEST and I may now close this ticket?

Regards,
Vasilis

**Comment by advacom** [comment]
Hi Vasilis,

Thanks for your reply, now it's clear what's happening.

Thanks again and as far as I am concerned you can close the ticket.

**Comment by vmavromatis** [comment]
No worries, happy to help.

**Comment by advacom** [comment]
Goodmorning Vasilis,

Unfortunately I'm getting the same error message "BOOKING_CONFIRM, Price changed during the booking process" again. Could you please be so kind to check again?

Thanks

**Comment by travelta** [comment]
Im also facing this issue. rateType is bookable, but got the price is changed notice. I did try to book on a date in dec. of 2019

**Comment by vmavromatis** [comment]
@travelta This is a known issue for the TEST environemnt, Please contact apitude@hotelbeds.com and ask the team to increase your price tolerance for the TEST environment only (this will not affect production). If you can share your apikey (no secret) I can help speed up the process.

Regards,
Vasilis

**Comment by travelta** [comment]
hey Vasilis,

My Api key is srxqca6z9prq83sge9ttkvdx. Do i still need to contact support or do you pick this up?

**Comment by vmavromatis** [comment]
Hi @travelta please send the email and I will make sure it receives proper attention.

**Comment by travelta** [comment]
hi @vmavromatis I did send the mail and got a reply : 

> This is not possible for the Test environment.
> We can suggest to test with the hotel 4172 (Hcc Regente) in Barcelona to perform Test bookings.

I do get the same responses(bookable type, but Price changed during the booking process), what can i do next?

I can see that during the recheck i even get the same price returned

**Comment by vmavromatis** [comment]
@travelta I raised the tolerance can you please give it a go and see if it works? Note, it may take a few minutes to propagate the change in the system.

**Comment by vmavromatis** [comment]
@travelta can you please confirm if you are now able to book? If so, please close this issue.

Regards,
Vasilis

**Comment by travelta** [comment]
@vmavromatis I can confirm its working now. Thanks for the effort
